### ISSUE TITLE
REQ: Add support Bearer Token

### ISSUE THREAD

**Issue by jhofstede** [boxboat/okta-nginx#11]
Hi,

Many thanks for providing this container. Would it be possible to add the ability to get the JWT from a `Authorization`-header?
```
Authorization: Bearer <token>
```
We want to fire AJAX-requests to the NGNIX server, cross origin, so there is no way to redirect the AJAX call to OKTA, and the browser refuses to manually craft a Cookie to send along with the request. We can set an `Authorization`-header to the request, but the solution in this repo only looks at JWT tokens in the Cookie.

Possible flow:
- Check `Authorization`-header is present, take JWT from there
- If not provided, check for token in Cookie.

The folks of Ory (https://github.com/ory/fosite) have done a similar thing, they try to fetch the token from multiple places, one of them being the `Authorization`-header:
https://github.com/ory/fosite/blob/211b43b4c04c732adc5fbfa7cab339f44fbea7d7/introspect.go#L36

If I would have any experience of Go, I would have made a PR, but unfortunately I don't.

Many thanks in advance!

**Comment by caleblloyd** [comment]
It is possible, but the goal of this proxy is to provide seamless authentication.  If a user is not logged in, it initiates the login flow.  It automatically refreshes tokens by placing a javascript snippet on HTML pages that are served.

With cross-domain calls using an `Authorization` header, this proxy could either pass-through the request if the JWT is valid or return a 401 if the JWT is invalid.  The app would need to handle initiating login flows and refreshing tokens.  Parameters for which hosts to allow to access CORS would also need to be added.

I'm not entirely against adding it, but it seems like a lot of application-specific logic that may be hard to generalize, and therefore may be better off done in your App.

**Comment by jhofstede** [comment]
Thanks for your reply. We've managed to implement the changed we needed. You can merge the PR if you see added value.
