### ISSUE TITLE
Latest tagged docker image throws an error

### ISSUE THREAD

**Issue by jlundy2** [boxboat/okta-nginx#27]
I've been using the okta-nginx docker image for about 3 years, but yesterday the new tagged docker image broke my setup.
Now it throws 
`unknown "detect_connection" variable`
when starting up.

More detailed logs:
```
Feb 22 04:54:26 ip-172-32-3-235 docker[676]: 2023/02/22 04:54:26 [emerg] 83#83: unknown "detect_connection" variable
Feb 22 04:54:26 ip-172-32-3-235 docker[676]: nginx: [emerg] unknown "detect_connection" variable
Feb 22 04:54:26 ip-172-32-3-235 docker[676]: nginx has died
```

**Comment by caleblloyd** [comment]
That variable was removed in #24 now it uses this to pass through connection and upgrade headers:

https://github.com/boxboat/okta-nginx/blob/75c1b961b471747e9699ac05b352df6490f2915c/stage/etc/nginx/includes/proxy-headers.conf#L9-L10

So if you were using `$detect_connection` or `$detect_upgrade` in a config file mounted into the container, switch those to use `$connection_upgrade` and `$http_upgrade`, respectively
